export type Exercise={id:string;name:string;type:string;location:string;bodyParts:string[];equipment:string;difficulty:string;description:string;instructions:string;videoUrl:string;sets?:number;reps?:string;duration?:string;rest?:string};
export type Session={id:string;title:string;day:string;type:string;duration:number;focus:string;warmup:string[];notes:string;exercises:Exercise[]};
export type Metric={date:string;weight:number;height:number;energy:number;pullups:number;trapbar:number};
export const exercises:Exercise[]=[
{id:'bench',name:'Bench Press',type:'Strength',location:'Gym',bodyParts:['Chest','Shoulders','Triceps','Core'],equipment:'Barbell, bench',difficulty:'Intermediate',description:'Upper push compound lift',instructions:'Feet planted, shoulder blades squeezed, lower with control and press smoothly.',videoUrl:'',sets:4,reps:'8-10',rest:'90-150 sec'},
{id:'incline-db',name:'Incline Dumbbell Press',type:'Strength',location:'Gym',bodyParts:['Chest','Shoulders','Triceps'],equipment:'Dumbbells, incline bench',difficulty:'Beginner',description:'Upper chest accessory press',instructions:'Use a slight incline. Keep wrists stacked and avoid bouncing at the bottom.',videoUrl:'',sets:3,reps:'10-12',rest:'60-90 sec'},
{id:'shoulder-press',name:'Seated Shoulder Press',type:'Strength',location:'Gym',bodyParts:['Shoulders','Triceps','Core'],equipment:'Dumbbells or machine',difficulty:'Beginner',description:'Vertical press',instructions:'Brace ribs down, press overhead, do not arch the lower back.',videoUrl:'',sets:3,reps:'10-12'},
{id:'lateral-raise',name:'Dumbbell Lateral Raise',type:'Strength',location:'Gym',bodyParts:['Shoulders'],equipment:'Dumbbells',difficulty:'Beginner',description:'Side delt isolation',instructions:'Soft elbows, raise to shoulder height, pause briefly, lower slowly.',videoUrl:'',sets:3,reps:'12-15'},
{id:'tricep-pushdown',name:'Cable Tricep Pushdown',type:'Strength',location:'Gym',bodyParts:['Triceps'],equipment:'Cable',difficulty:'Beginner',description:'Triceps isolation',instructions:'Elbows close to body. Extend fully without leaning over the cable.',videoUrl:'',sets:3,reps:'12-15'},
{id:'plank',name:'Plank',type:'Core',location:'Home',bodyParts:['Core','Abs'],equipment:'Bodyweight',difficulty:'Beginner',description:'Anti-extension core hold',instructions:'Straight line from head to heels. Squeeze glutes and breathe slowly.',videoUrl:'',sets:3,reps:'45 sec'},
{id:'back-squat',name:'Back Squat',type:'Strength',location:'Gym',bodyParts:['Quadriceps','Glutes','Hamstrings','Core'],equipment:'Barbell, rack',difficulty:'Intermediate',description:'Lower body compound lift',instructions:'Brace first, knees track over toes, control depth, drive through mid-foot.',videoUrl:'',sets:4,reps:'8-10'},
{id:'rdl',name:'Romanian Deadlift',type:'Strength',location:'Gym',bodyParts:['Hamstrings','Glutes','Back'],equipment:'Barbell or dumbbells',difficulty:'Intermediate',description:'Hip hinge strength',instructions:'Hips move back, spine neutral, feel hamstrings, stand tall without leaning back.',videoUrl:'',sets:3,reps:'10'},
{id:'walking-lunge',name:'Walking Lunge',type:'Strength',location:'Gym',bodyParts:['Quadriceps','Glutes','Hamstrings'],equipment:'Bodyweight or dumbbells',difficulty:'Beginner',description:'Unilateral leg strength',instructions:'Long controlled stride, back knee drops, front foot stays flat.',videoUrl:'',sets:3,reps:'12/leg'},
{id:'leg-press',name:'Leg Press',type:'Strength',location:'Gym',bodyParts:['Quadriceps','Glutes'],equipment:'Leg press',difficulty:'Beginner',description:'Lower body accessory',instructions:'Control platform, avoid hard knee lockout, keep lower back on pad.',videoUrl:'',sets:3,reps:'12'},
{id:'calf-raise',name:'Standing Calf Raise',type:'Strength',location:'Gym',bodyParts:['Calves'],equipment:'Machine or dumbbells',difficulty:'Beginner',description:'Calf strength',instructions:'Full stretch at bottom, strong squeeze at top, slow tempo.',videoUrl:'',sets:4,reps:'15'},
{id:'knee-raise',name:'Hanging Knee Raise',type:'Core',location:'Gym',bodyParts:['Abs','Core'],equipment:'Pull-up bar',difficulty:'Intermediate',description:'Core flexion',instructions:'Avoid swinging. Curl pelvis upward and control the lowering phase.',videoUrl:'',sets:3,reps:'15'},
{id:'lat-pulldown',name:'Lat Pulldown',type:'Strength',location:'Gym',bodyParts:['Back','Biceps'],equipment:'Cable machine',difficulty:'Beginner',description:'Vertical pull',instructions:'Pull elbows down, chest tall, do not yank with lower back.',videoUrl:'',sets:4,reps:'8-12'},
{id:'cable-row',name:'Seated Cable Row',type:'Strength',location:'Gym',bodyParts:['Back','Biceps','Rear Delts'],equipment:'Cable row',difficulty:'Beginner',description:'Horizontal pull',instructions:'Pull to lower ribs, pause, let shoulder blades glide forward under control.',videoUrl:'',sets:3,reps:'10-12'},
{id:'db-row',name:'Single Arm Dumbbell Row',type:'Strength',location:'Gym',bodyParts:['Back','Biceps','Core'],equipment:'Dumbbell, bench',difficulty:'Beginner',description:'Single-arm row',instructions:'Brace one hand, pull elbow toward hip, keep torso stable.',videoUrl:'',sets:3,reps:'10/side'},
{id:'face-pull',name:'Face Pull',type:'Strength',location:'Gym',bodyParts:['Rear Delts','Shoulders','Upper Back'],equipment:'Cable/rope',difficulty:'Beginner',description:'Shoulder health',instructions:'Pull toward face with elbows high. Great for posture.',videoUrl:'',sets:3,reps:'15'},
{id:'curl',name:'Dumbbell Bicep Curl',type:'Strength',location:'Gym',bodyParts:['Biceps'],equipment:'Dumbbells',difficulty:'Beginner',description:'Biceps isolation',instructions:'Elbows stay still, no swinging, squeeze at the top.',videoUrl:'',sets:3,reps:'12'},
{id:'hammer',name:'Hammer Curl',type:'Strength',location:'Gym',bodyParts:['Biceps','Forearms'],equipment:'Dumbbells',difficulty:'Beginner',description:'Arm and grip accessory',instructions:'Neutral grip, control both directions, build biceps and forearms.',videoUrl:'',sets:3,reps:'12'},
{id:'trapbar',name:'Trap Bar Deadlift',type:'Strength',location:'Gym',bodyParts:['Glutes','Hamstrings','Back','Grip'],equipment:'Trap bar',difficulty:'Intermediate',description:'Athletic hinge lift',instructions:'Hips and chest rise together. Push the floor away and keep bar path close.',videoUrl:'',sets:4,reps:'6-8'},
{id:'db-bench',name:'Dumbbell Bench Press',type:'Strength',location:'Gym',bodyParts:['Chest','Shoulders','Triceps'],equipment:'Dumbbells, bench',difficulty:'Beginner',description:'Pressing accessory',instructions:'Control the bells, keep shoulders packed, press evenly.',videoUrl:'',sets:3,reps:'10'},
{id:'pullup',name:'Pull Up or Assisted Pull Up',type:'Strength',location:'Gym',bodyParts:['Back','Biceps','Grip'],equipment:'Pull-up bar or machine',difficulty:'Intermediate',description:'Vertical pull strength',instructions:'Start from a controlled hang, pull chest upward, stop before form breaks.',videoUrl:'',sets:3,reps:'Max quality'},
{id:'split-squat',name:'Bulgarian Split Squat',type:'Strength',location:'Gym',bodyParts:['Quadriceps','Glutes','Hamstrings','Core'],equipment:'Bench, dumbbells optional',difficulty:'Intermediate',description:'Unilateral leg strength',instructions:'Front foot planted, torso tall, slow controlled lowering.',videoUrl:'',sets:3,reps:'10/leg'},
{id:'farmer',name:'Farmer Carry',type:'Conditioning',location:'Gym',bodyParts:['Grip','Core','Traps','Full Body'],equipment:'Dumbbells/kettlebells',difficulty:'Beginner',description:'Grip and trunk carry',instructions:'Stand tall, ribs down, crush handles, walk with short strong steps.',videoUrl:'',sets:4,reps:'30m'},
{id:'woodchopper',name:'Cable Woodchopper',type:'Core',location:'Gym',bodyParts:['Core','Obliques'],equipment:'Cable',difficulty:'Beginner',description:'Rotational trunk control',instructions:'Rotate through trunk and hips. Control the return, do not rush.',videoUrl:'',sets:3,reps:'12/side'},
{id:'ladder',name:'Ladder Drills',type:'Footwork',location:'Home',bodyParts:['Cardio','Calves','Coordination'],equipment:'Agility ladder',difficulty:'Beginner',description:'Fast feet and rhythm',instructions:'Stay light on toes, keep posture tall, build clean rhythm before speed.',videoUrl:'',duration:'3 mins'},
{id:'marker-angle',name:'Marker Angle Drills',type:'Footwork',location:'Home',bodyParts:['Footwork','Coordination'],equipment:'Markers/cones',difficulty:'Beginner',description:'Angle changes for striking',instructions:'Step in and out at angles, reset stance after every movement.',videoUrl:'',duration:'3 mins'},
{id:'slip-rope',name:'Slip Rope Movement',type:'Boxing',location:'Home',bodyParts:['Core','Footwork'],equipment:'Slip rope/string',difficulty:'Beginner',description:'Head movement and footwork',instructions:'Move under the rope with small steps, keep eyes forward and guard high.',videoUrl:'',duration:'3 mins'},
{id:'shadow-metronome',name:'Shadowboxing to Metronome',type:'Boxing',location:'Home',bodyParts:['Cardio','Coordination','Full Body'],equipment:'Metronome app',difficulty:'Beginner',description:'Rhythm and tempo',instructions:'Move to the beat, keep combinations smooth, breathe naturally.',videoUrl:'',duration:'3 mins'},
{id:'tennis-ball',name:'Free Movement Around Tennis Ball',type:'Footwork',location:'Home',bodyParts:['Footwork','Reaction'],equipment:'Tennis ball',difficulty:'Beginner',description:'Movement awareness',instructions:'Circle, enter, exit and reset stance around the tennis ball.',videoUrl:'',duration:'3 mins'}
];
const e=(id:string)=>exercises.find(x=>x.id===id)!;
export const sessions:Session[]=[
{id:'push',title:'Day 1 - Upper Push',day:'Monday',type:'Gym',duration:60,focus:'Chest, shoulders, triceps and core',warmup:['Band pull-aparts x 15','Scap push-ups x 10','Light dumbbell press x 12','Shoulder external rotations x 12 each side'],notes:'Keep 1-3 reps in reserve. Add weight only when every rep is controlled.',exercises:['bench','incline-db','shoulder-press','lateral-raise','tricep-pushdown','plank'].map(e)},
{id:'lower',title:'Day 2 - Lower Body',day:'Tuesday',type:'Gym',duration:60,focus:'Quads, hamstrings, glutes, calves and core',warmup:['Bodyweight squats x 12','Reverse lunges x 8 each side','Glute bridges x 12','Hamstring sweeps x 8 each side'],notes:'Control depth, brace well and avoid ego lifting.',exercises:['back-squat','rdl','walking-lunge','leg-press','calf-raise','knee-raise'].map(e)},
{id:'pull',title:'Day 3 - Upper Pull',day:'Thursday',type:'Gym',duration:60,focus:'Back, rear delts, biceps and grip',warmup:['Row machine 3 mins','Band rows x 15','Dead hangs 2 x 15 seconds','Face pulls x 15'],notes:'Focus on posture, shoulder health and grip transfer to BJJ.',exercises:['lat-pulldown','cable-row','db-row','face-pull','curl','hammer'].map(e)},
{id:'full',title:'Day 4 - Full Body Athletic',day:'Saturday',type:'Gym',duration:60,focus:'Posterior chain, unilateral legs, push/pull and carries',warmup:['Dynamic lunges','Light kettlebell deadlifts','Shoulder taps','Low-intensity carries'],notes:'Athletic quality session. Finish strong but not destroyed.',exercises:['trapbar','db-bench','pullup','split-squat','farmer','woodchopper'].map(e)},
{id:'footwork',title:'15-Minute Daily Footwork Routine',day:'Daily',type:'Home',duration:15,focus:'MMA footwork, rhythm and movement',warmup:['Easy bounce and stance switches x 60 sec'],notes:'Complete daily when possible. Quality movement over speed.',exercises:['ladder','marker-angle','slip-rope','shadow-metronome','tennis-ball'].map(e)}
];
export const metrics:Metric[]=[{date:'Start',weight:62,height:172,energy:7,pullups:4,trapbar:50},{date:'Week 4',weight:63.2,height:172,energy:8,pullups:6,trapbar:60},{date:'Week 8',weight:64.4,height:172,energy:8,pullups:8,trapbar:72.5},{date:'Week 12',weight:65.1,height:172,energy:9,pullups:10,trapbar:85}];
export const badges=['First Workout','7-Day Streak','Footwork Starter','Push Session Complete','Pull-Up Progress','100 Sessions','FMA Attendance','12-Week Finisher'];
