import React,{useMemo,useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {Activity,Award,CalendarDays,CheckCircle2,ChevronRight,Dumbbell,Flame,Home,Library,LineChart,Lock,Plus,Shield,Timer,User,Video,Settings,ClipboardList,Medal} from 'lucide-react';
import {ResponsiveContainer,LineChart as RLineChart,Line,XAxis,YAxis,Tooltip,BarChart,Bar,CartesianGrid} from 'recharts';
import {exercises,sessions,metrics,badges,Exercise,Session} from './data';
import './styles.css';

const supabaseUrl=import.meta.env.VITE_SUPABASE_URL as string|undefined;
const supabaseKey=import.meta.env.VITE_SUPABASE_ANON_KEY as string|undefined;
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;
type Tab='Dashboard'|'Today'|'Calendar'|'Exercises'|'Builder'|'Classes'|'Admin'|'Profile';
const nav:Tab[]=['Dashboard','Today','Calendar','Exercises','Builder','Classes','Admin','Profile'];
const ls={get<T>(k:string,d:T){try{return JSON.parse(localStorage.getItem(k)||'') as T}catch{return d}},set(k:string,v:any){localStorage.setItem(k,JSON.stringify(v))}};
function Badge({children}:{children:React.ReactNode}){return <span className="badge">{children}</span>}
function Card({children,wide=false}:{children:React.ReactNode;wide?:boolean}){return <section className={wide?'card wide':'card'}>{children}</section>}
function App(){const [user,setUser]=useState<any>(null);const [demo,setDemo]=useState(!supabase);const [tab,setTab]=useState<Tab>('Dashboard');useEffect(()=>{supabase?.auth.getUser().then(({data})=>setUser(data.user));},[]);if(!user&&!demo)return <Login onDemo={()=>setDemo(true)} onUser={setUser}/>;return <div className="shell"><aside><div className="brand"><Shield/><div><b>BlackBeltBootcamp</b><small>Combat sport training OS</small></div></div>{nav.map(n=><button key={n} onClick={()=>setTab(n)} className={tab===n?'active':''}>{icons[n]}<span>{n}</span></button>)}<div className="asideNote"><Lock size={16}/> {demo?'Demo/local mode':'Supabase connected'}</div></aside><main><header><div><p className="eyebrow">James Hiles • 12-week athlete development</p><h1>{title(tab)}</h1></div><div className="userPill"><div className="avatar">JH</div><div><b>James</b><small>MMA • BJJ • Strength</small></div></div></header>{tab==='Dashboard'&&<Dashboard/>}{tab==='Today'&&<Today/>}{tab==='Calendar'&&<Calendar/>}{tab==='Exercises'&&<ExerciseDirectory/>}{tab==='Builder'&&<Builder/>}{tab==='Classes'&&<Classes/>}{tab==='Admin'&&<Admin/>}{tab==='Profile'&&<Profile/>}</main></div>}
const icons:Record<Tab,React.ReactNode>={Dashboard:<Home/>,Today:<Dumbbell/>,Calendar:<CalendarDays/>,Exercises:<Library/>,Builder:<Plus/>,Classes:<ClipboardList/>,Admin:<Settings/>,Profile:<User/>};
const title=(t:Tab)=>({Dashboard:'Performance Dashboard',Today:"Today's Training",Calendar:'Training Calendar',Exercises:'Exercise Directory',Builder:'Workout Builder',Classes:'FMA Chester Classes',Admin:'Admin Console',Profile:'Athlete Profile'}[t]);
function Login({onDemo,onUser}:{onDemo:()=>void;onUser:(u:any)=>void}){const[email,setEmail]=useState('');const[pw,setPw]=useState('');const[msg,setMsg]=useState('');async function login(){if(!supabase)return onDemo();const {data,error}=await supabase.auth.signInWithPassword({email,password:pw});if(error)setMsg(error.message);else onUser(data.user)}return <div className="login"><Card><div className="brand big"><Shield/><div><b>BlackBeltBootcamp</b><small>Login</small></div></div><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={pw} onChange={e=>setPw(e.target.value)}/><button className="primary" onClick={login}>Sign in</button><button onClick={onDemo}>Open demo mode</button><p className="muted">{msg||'Use demo mode while you finish Supabase authentication setup.'}</p></Card></div>}
function Dashboard(){const done=ls.get<Record<string,boolean>>('done',{});const completed=Object.values(done).filter(Boolean).length;const chart=metrics.map((m,i)=>({...m,session:i*4+4,bmi:Math.round((m.weight/((m.height/100)**2))*10)/10}));return <div className="grid"><Card wide><div className="hero"><div><p className="eyebrow">Current programme</p><h2>12-Week BlackBeltBootcamp Base Programme</h2><p>Four 60-minute gym sessions each week, daily footwork, progressive overload, recovery habits and MMA/BJJ carryover.</p><div className="row"><Badge>4 gym sessions/week</Badge><Badge>15-min daily footwork</Badge><Badge>Target effort 7-8/10</Badge></div></div><Medal className="heroIcon"/></div></Card><Kpi icon={<Flame/>} label="Current streak" value="5 days" hint="7-day badge in reach"/><Kpi icon={<CheckCircle2/>} label="Today" value={`${completed}`} hint="exercises completed"/><Kpi icon={<Timer/>} label="Weekly target" value="42/48" hint="12-week consistency goal"/><Card wide><h3><LineChart/> Strength & body metrics</h3><ResponsiveContainer width="100%" height={260}><RLineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Line type="monotone" dataKey="trapbar" strokeWidth={3}/><Line type="monotone" dataKey="pullups" strokeWidth={3}/><Line type="monotone" dataKey="bmi" strokeWidth={3}/></RLineChart></ResponsiveContainer></Card><Card wide><h3><Activity/> Training sessions</h3><ResponsiveContainer width="100%" height={240}><BarChart data={chart}><XAxis dataKey="date"/><YAxis/><Tooltip/><Bar dataKey="session" radius={8}/></BarChart></ResponsiveContainer></Card><Card><h3><Award/> Badges</h3><div className="badgeGrid">{badges.map(b=><Badge key={b}>{b}</Badge>)}</div></Card></div>}
function Kpi({icon,label,value,hint}:{icon:React.ReactNode;label:string;value:string;hint:string}){return <Card><h3>{icon}{label}</h3><div className="kpi">{value}</div><p className="muted">{hint}</p></Card>}
function Today(){const [session,setSession]=useState<Session>(sessions[0]);const [done,setDone]=useState(ls.get<Record<string,boolean>>('done',{}));const [logs,setLogs]=useState<Record<string,any>>(ls.get('logs',{}));function toggle(id:string){const n={...done,[id]:!done[id]};setDone(n);ls.set('done',n)}function saveLog(id:string,k:string,v:string){const n={...logs,[id]:{...logs[id],[k]:v}};setLogs(n);ls.set('logs',n)}return <div className="layout2"><Card><div className="split"><div><p className="eyebrow">{session.day} • {session.duration} mins</p><h2>{session.title}</h2><p>{session.focus}</p></div><Badge>{session.type}</Badge></div><h3>Warm-up</h3><ul>{session.warmup.map(w=><li key={w}>{w}</li>)}</ul><h3>Workout</h3>{session.exercises.map(ex=><LogExercise key={ex.id} ex={ex} done={!!done[ex.id]} toggle={()=>toggle(ex.id)} logs={logs[ex.id]||{}} save={(k,v)=>saveLog(ex.id,k,v)}/>)}</Card><Card><h3>Select session</h3>{sessions.map(s=><button className="sessionBtn" key={s.id} onClick={()=>setSession(s)}><span><b>{s.title}</b><small>{s.day} • {s.duration} mins • {s.type}</small></span><ChevronRight/></button>)}<h3>Coach notes</h3><p>{session.notes}</p></Card></div>}
function LogExercise({ex,done,toggle,logs,save}:{ex:Exercise;done:boolean;toggle:()=>void;logs:any;save:(k:string,v:string)=>void}){return <div className="log"><div className="vid">{ex.videoUrl?<iframe src={ex.videoUrl}/>:<><Video/><small>Add demo URL in Admin</small></>}</div><div className="logBody"><h4>{ex.name}</h4><p>{ex.instructions}</p><div className="row"><Badge>{ex.sets?`${ex.sets} sets`:ex.duration}</Badge><Badge>{ex.reps||'Timed'}</Badge><Badge>{ex.bodyParts.slice(0,3).join(', ')}</Badge></div><div className="inputs">{Array.from({length:ex.sets||1}).slice(0,4).map((_,i)=><React.Fragment key={i}><input value={logs[`kg${i}`]||''} onChange={e=>save(`kg${i}`,e.target.value)} placeholder={`Set ${i+1} kg`}/><input value={logs[`reps${i}`]||''} onChange={e=>save(`reps${i}`,e.target.value)} placeholder="reps/time"/></React.Fragment>)}</div></div><button className={done?'complete done':'complete'} onClick={toggle}>{done?'Done':'Complete'}</button></div>}
function Calendar(){return <div className="calendarGrid">{Array.from({length:12},(_,i)=>i+1).map(w=><Card key={w}><h3>Week {w}</h3><p className="muted">{w<3?'Foundation: movement quality':w<7?'Build: volume and consistency':w<11?'Performance: intensity and speed':'Deload/test quality'}</p>{sessions.slice(0,4).map(s=><div className="mini" key={s.id}><span>{s.day}</span><b>{s.title.replace('Day ','D')}</b><input type="checkbox"/></div>)}</Card>)}</div>}
function ExerciseDirectory(){const[part,setPart]=useState('All');const[query,setQuery]=useState('');const[loc,setLoc]=useState('All');const parts=['All',...Array.from(new Set(exercises.flatMap(e=>e.bodyParts))).sort()];const locs=['All',...Array.from(new Set(exercises.map(e=>e.location))).sort()];const filtered=exercises.filter(e=>(part==='All'||e.bodyParts.includes(part))&&(loc==='All'||e.location===loc)&&(e.name.toLowerCase().includes(query.toLowerCase())||e.type.toLowerCase().includes(query.toLowerCase())));return <><div className="toolbar"><input placeholder="Search exercises" value={query} onChange={e=>setQuery(e.target.value)}/><select value={part} onChange={e=>setPart(e.target.value)}>{parts.map(p=><option key={p}>{p}</option>)}</select><select value={loc} onChange={e=>setLoc(e.target.value)}>{locs.map(l=><option key={l}>{l}</option>)}</select></div><div className="cards3">{filtered.map(ex=><Card key={ex.id}><div className="vid small"><Video/></div><h3>{ex.name}</h3><p>{ex.description}</p><div className="row"><Badge>{ex.type}</Badge><Badge>{ex.location}</Badge><Badge>{ex.difficulty}</Badge></div><p className="muted">{ex.bodyParts.join(' • ')}</p></Card>)}</div></>}
function Builder(){const[chosen,setChosen]=useState<string[]>([]);return <div className="layout2"><Card><h2>Workout builder</h2><input placeholder="Workout name"/><select><option>Gym</option><option>Home</option><option>FMA Chester</option><option>Outdoors</option></select><textarea placeholder="Coach or athlete notes"/><button className="primary">Save workout template</button><h3>Selected exercises</h3>{chosen.length?chosen.map(id=><Badge key={id}>{exercises.find(e=>e.id===id)?.name}</Badge>):<p className="muted">No exercises selected yet.</p>}</Card><Card><h3>Pick exercises</h3>{exercises.slice(0,16).map(e=><button className="sessionBtn" key={e.id} onClick={()=>setChosen(c=>c.includes(e.id)?c:[...c,e.id])}><span><b>{e.name}</b><small>{e.type} • {e.location}</small></span><Plus/></button>)}</Card></div>}
function Classes(){const[fma,setFma]=useState(ls.get<any[]>('fma',[{name:'Advanced Class',day:'Manual',time:'TBC',level:'Advanced'},{name:'Masters Class',day:'Manual',time:'TBC',level:'Masters'},{name:'Adult Class',day:'Manual',time:'TBC',level:'Adult'}]));const[planned,setPlanned]=useState(ls.get<Record<string,boolean>>('plannedClasses',{}));function plan(i:number){const n={...planned,[i]:!planned[i]};setPlanned(n);ls.set('plannedClasses',n)}return <div className="layout2"><Card><h2>FMA Chester class diary</h2><p>Manually add the FMA timetable, then James can choose which sessions he plans to attend.</p>{fma.map((c,i)=><div className="mini" key={i}><span>{c.day} {c.time}</span><b>{c.name}</b><Badge>{c.level}</Badge><button onClick={()=>plan(i)}>{planned[i]?'Planned':'Add'}</button></div>)}</Card><Card><h3>Add class</h3><ClassForm onAdd={(c:any)=>{const n=[...fma,c];setFma(n);ls.set('fma',n)}}/></Card></div>}
function ClassForm({onAdd}:{onAdd:(c:any)=>void}){const[c,setC]=useState({name:'',day:'',time:'',level:''});return <><input placeholder="Class name" onChange={e=>setC({...c,name:e.target.value})}/><input placeholder="Day" onChange={e=>setC({...c,day:e.target.value})}/><input placeholder="Time" onChange={e=>setC({...c,time:e.target.value})}/><input placeholder="Level" onChange={e=>setC({...c,level:e.target.value})}/><button className="primary" onClick={()=>onAdd(c)}>Add class</button></>}
function Admin(){const[custom,setCustom]=useState(ls.get<Exercise[]>('customExercises',[]));const[c,setC]=useState<Partial<Exercise>>({type:'Strength',location:'Gym',difficulty:'Beginner',bodyParts:[]});function add(){if(!c.name)return;const ex={id:crypto.randomUUID(),description:'Custom exercise',instructions:c.instructions||'',equipment:c.equipment||'',videoUrl:c.videoUrl||'',bodyParts:String((c as any).bodyText||'Full Body').split(',').map((x:string)=>x.trim()),...c} as Exercise;const n=[...custom,ex];setCustom(n);ls.set('customExercises',n)}return <div className="layout2"><Card><h2>Admin exercise entry</h2><input placeholder="Exercise name" onChange={e=>setC({...c,name:e.target.value})}/><select onChange={e=>setC({...c,type:e.target.value})}><option>Strength</option><option>MMA</option><option>Boxing</option><option>Kickboxing</option><option>BJJ</option><option>Footwork</option><option>Physio</option><option>Mobility</option></select><select onChange={e=>setC({...c,location:e.target.value})}><option>Gym</option><option>Home</option><option>FMA Chester</option><option>Outdoors</option></select><input placeholder="Equipment" onChange={e=>setC({...c,equipment:e.target.value})}/><input placeholder="Body parts, comma separated" onChange={e=>setC({...c,bodyText:e.target.value} as any)}/><input placeholder="Demo video URL" onChange={e=>setC({...c,videoUrl:e.target.value})}/><textarea placeholder="Instructions" onChange={e=>setC({...c,instructions:e.target.value})}/><button className="primary" onClick={add}>Add exercise</button></Card><Card><h3>ExerciseDB Pro import staging</h3><p>Later version: upload the JSON file and map name, bodyPart, target, equipment, instructions, gif/video URL and secondary muscles into Supabase.</p><input type="file" accept=".json"/><h3>Custom exercises</h3>{custom.map(e=><div className="mini" key={e.id}><b>{e.name}</b><span>{e.type}</span></div>)}</Card></div>}
function Profile(){const[m,setM]=useState(ls.get<any>('profile',{height:172,weight:62,goal:'Build lean muscle, strength, athletic movement and MMA/BJJ durability.'}));function upd(k:string,v:string){const n={...m,[k]:v};setM(n);ls.set('profile',n)}const bmi=m.height&&m.weight?(m.weight/((m.height/100)**2)).toFixed(1):'';return <div className="layout2"><Card><h2>James Hiles</h2><div className="profileBlock"><div className="avatar big">JH</div><div><Badge>MMA</Badge><Badge>BJJ</Badge><Badge>Strength</Badge><Badge>Footwork</Badge></div></div><label>Height cm<input value={m.height} onChange={e=>upd('height',e.target.value)}/></label><label>Weight kg<input value={m.weight} onChange={e=>upd('weight',e.target.value)}/></label><label>BMI<input value={bmi} readOnly/></label><label>Goals<textarea value={m.goal} onChange={e=>upd('goal',e.target.value)}/></label></Card><Card><h3>Sunday review</h3>{['Did I complete all planned sessions?','Which lift improved this week?','How was my sleep?','Did gym training help or hurt MMA/BJJ performance?','What is the single focus for next week?'].map(q=><label key={q}>{q}<textarea/></label>)}</Card></div>}
createRoot(document.getElementById('root')!).render(<App/>);
